# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

degSpecificSigcpp <- function(x, seed, deg, par) {
    .Call('_DEComplexDisease_degSpecificSigcpp', PACKAGE = 'DEComplexDisease', x, seed, deg, par)
}

degSharedSigcpp <- function(x, seed, deg, par) {
    .Call('_DEComplexDisease_degSharedSigcpp', PACKAGE = 'DEComplexDisease', x, seed, deg, par)
}

